### ISSUE TITLE
Changes in pymdown-extensions break command-line invocation

### ISSUE THREAD

**Issue by socketbox** [ncornette/Python-Markdown-Editor#15]
Version 5.0 (released Aug 18) of [pymdown-extensions](https://github.com/facelessuser/pymdown-extensions) [deprecates the github extension](https://github.com/facelessuser/pymdown-extensions/releases).

This generates the following stacktrace when I run `markdown_editor README.md`:

```
Traceback (most recent call last):                                                                                                      │Icon-32.png         Info.plist          error.html          images              modals
  File "/Users/chb/.pyenv/versions/3.7.0/envs/mrkdwn/lib/python3.7/site-packages/markdown/__init__.py", line 231, in build_extension    │Icon-48.png         Settings.plist      format.txt          injection.js        overview
    module = importlib.import_module(ext_name)                                                                                          │Icon-64.png         circle.png          global.html         intro.html          sessions-export.zip
  File "/Users/chb/.pyenv/versions/3.7.0/lib/python3.7/importlib/__init__.py", line 127, in import_module                               │[chb-mbp-sierra:Sessions.safariextension chb]$ grep export *
    return _bootstrap._gcd_import(name[level:], package, level)                                                                         │global.js:      // which used to differ from the export format.
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                                       │global.js:                      // This version and above are identical to the export format as described in format.txt.
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                                     │global.js:var exportSessions = (function () {
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked                                                            │global.js:                              '\t<!-- NOTICE: This format is deprecated as an export and import option for Sessions. -->',
ModuleNotFoundError: No module named 'pymdownx.github'                                                                                  │global.js:      return function (exportFormat, sessionIDs, failCallback, completeCallback) {
                                                                                                                                        │global.js:              format[exportFormat](sessionIDs);
During handling of the above exception, another exception occurred:
...
```
`markdown` then tries a few other variations on module naming conventions before giving up.

I edited `markdown_editor/editor.py` such that the pymdown-extension tuple included a different extension (`arithmatex` in lieu of `github`). But given that the user has the option of naming their own with `-x`, maybe not include any by default?

**Comment by ncornette** [comment]
Thank you for the report! I will fix it soon

**Comment by lesatdgl** [comment]
**I'm getting this same error with pipenv install markdown-editor**

Install works - from pipenv graph: 
Markdown-Editor==1.0.3
  - bottle [required: Any, installed: 0.12.16]
  - Markdown [required: Any, installed: 3.1]
    - setuptools [required: >=36, installed: 40.8.0]
  - Pygments [required: Any, installed: 2.3.1]
  - pymdown-extensions [required: >=2.0, installed: 6.0]
    - Markdown [required: >=3.0.1, installed: 3.1]
      - setuptools [required: >=36, installed: 40.8.0]

**Invoking from cmdline in python 3.6.7**
 markdown_edit
Traceback (most recent call last):
  File "/home/les/.local/share/virtualenvs/pelican-projects-xtj21HM1/bin/markdown_edit", line 10, in <module>
    sys.exit(main())
  File "/home/les/.local/share/virtualenvs/pelican-projects-xtj21HM1/lib/python3.6/site-packages/markdown_edit.py", line 95, in main
    markdown_processor = markdown.Markdown(**options)
  File "/home/les/.local/share/virtualenvs/pelican-projects-xtj21HM1/lib/python3.6/site-packages/markdown/core.py", line 100, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/les/.local/share/virtualenvs/pelican-projects-xtj21HM1/lib/python3.6/site-packages/markdown/core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/les/.local/share/virtualenvs/pelican-projects-xtj21HM1/lib/python3.6/site-packages/markdown/core.py", line 166, in build_extension
    module = importlib.import_module(ext_name)
  File "/home/les/.local/share/virtualenvs/pelican-projects-xtj21HM1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pymdownx.github'

**Comment by cknoll** [comment]
As far as I see, the problem still exists and will likely affect all people now installing via pip in a fresh environment.

The PR #18 of @zodman solves the problem for me.

Another workaround is `pip install "pymdown-extensions<4"`

**Comment by cknoll** [comment]
Update: The commandline

```
markdown_edit -x "markdown.extensions.tables" -x "pymdownx.magiclink" -x "pymdownx.betterem" -x "pymdownx.tilde" -x "pymdownx.emoji" -x "pymdownx.tasklist" -x "pymdownx.superfences" README.md
```

should resemble the now missing extension `pymdownx.github`.
