### ISSUE TITLE
Save and Preview Error in Chrome

### ISSUE THREAD

**Issue by neuroglobin** [ncornette/Python-Markdown-Editor#7]
Hi, 
I just tested the most recent master branch (downloaded as zip). When press save or preview button I always got the Error message
```
Traceback (most recent call last):
  File "D:\Program Files\WinPython-64bit-2.7.10.2\Python-Markdown-Editor-master\markdown_editor\editor.py", line 145, in do_POST
    content, keep_running = action_handler(self.server.app.document)
  File "D:\Program Files\WinPython-64bit-2.7.10.2\Python-Markdown-Editor-master\markdown_editor\editor.py", line 286, in action_save
    result = document.get_html_page()
  File "D:\Program Files\WinPython-64bit-2.7.10.2\Python-Markdown-Editor-master\markdown_editor\editor.py", line 232, in get_html_page
    """.format(self.inline_css, self.get_html())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 2936: ordinal not in range(128)
Continue editing
```
My environment is Windows 10, Chrome Version 50.0.2661.102 m, WinPython-64bit-2.7. 
Thanks!

**Comment by ncornette** [comment]
fixed #7
